# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Execute Tests
        run: |
          cd tests
          bazel test //...
